name: Dev Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build Package
        id: build_package
        run: ./build.sh --dev --download-deps

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(make print-version BUILD_TYPE=dev)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          LAST_STABLE_TAG=$(git tag --sort=-creatordate | grep -v "\-dev\-" | grep -v "^${VERSION}$" | head -n 1)
          echo "last_stable_tag=${LAST_STABLE_TAG}" >> $GITHUB_OUTPUT

      - name: Create Dev Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.get_version.outputs.version }}
          TARGET_COMMIT: ${{ github.sha }}
          LAST_STABLE_TAG: ${{ steps.get_version.outputs.last_stable_tag }}
          ELFLDR_VER: ${{ steps.build_package.outputs.elfldr_ver }}
          KEXP_VER: ${{ steps.build_package.outputs.kexp_ver }}
          AUTOLOADER_VER: ${{ steps.build_package.outputs.unified_autoloader_ver }}
        run: |
          cat <<EOF > release_notes.md
          - ### Changelog:

          **Full Changelog (since last stable release)**: https://github.com/${GITHUB_REPOSITORY}/compare/${LAST_STABLE_TAG}...${TAG_NAME}

          ---
          <details>
          <summary>Bundled Binaries</summary>

          This build integrates the following external dependency versions:
          - [itsPLK/ps5-elfldr](https://github.com/itsPLK/ps5-elfldr): [${ELFLDR_VER}](https://github.com/itsPLK/ps5-elfldr/releases/tag/${ELFLDR_VER})
          - [itsPLK/ps5-kexp](https://github.com/itsPLK/ps5-kexp): [${KEXP_VER}](https://github.com/itsPLK/ps5-kexp/releases/tag/${KEXP_VER})
          - [itsPLK/ps5-unified-autoloader](https://github.com/itsPLK/ps5-unified-autoloader): [${AUTOLOADER_VER}](https://github.com/itsPLK/ps5-unified-autoloader/releases/tag/${AUTOLOADER_VER})

          </details>
          EOF

          gh release create "$TAG_NAME" y2jb_update.zip \
            --target "$TARGET_COMMIT" \
            --title "$TAG_NAME" \
            --notes-file release_notes.md \
            --prerelease
